[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22.0.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_RUNTIME = "nodejs"

[[plugins]]
  package = "@netlify/plugin-nextjs"
