[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  # Add your TMDB API key here if not in Netlify Dashboard
  # TMDB_API_KEY = "your_api_key_here"

[[plugins]]
  package = "@netlify/plugin-nextjs"
